/**
 * API Adhésion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AdherentDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetByIdRequestParams {
    adherentId: number;
}


export interface AdherentControllerApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /adherent/getById
* @param requestParameters
     */
    getById(requestParameters: GetByIdRequestParams, extraHttpRequestParams?: any): Observable<AdherentDto>;

}
