/**
 * API Adhésion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccordDto { 
    id?: number;
    nom: string;
    title?: string;
    text?: string;
    valide?: string;
    refus?: string;
    refusable?: boolean;
    etat?: boolean;
    datePassage?: string;
}

