/**
 * API Adhésion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalleDto } from './salle';
import { PlanificationHebdomadaireDto } from './planification-hebdomadaire';
import { AdherentDto } from './adherent';


export interface ActiviteDto { 
    id?: number;
    groupe?: string;
    groupeFiltre?: string;
    groupeCompta?: string;
    nom?: string;
    lien?: string;
    tarif?: number;
    nbPlaces?: number;
    ageMin?: number;
    ageMax?: number;
    genre?: string;
    horaire?: string;
    salle?: SalleDto;
    reinscription?: boolean;
    globaleSpecifique?: boolean;
    priseEnCharge?: boolean;
    autorisationParentale?: boolean;
    vieClub?: boolean;
    charteAmicale?: boolean;
    jour?: ActiviteDtoJourEnum;
    horaireDebut?: string;
    duree?: number;
    planificationsHebdomadaires?: Array<PlanificationHebdomadaireDto>;
    certificatMedical?: boolean;
    complete?: boolean;
    majoration?: boolean;
    dureeVieCertif?: number;
    nbAdhesionsEnCours?: number;
    nbAdhesionsCompletes?: number;
    montantCollecte?: number;
    nbAdhesionsAttente?: number;
    nbSeancesRealisees?: number;
    nbSeancesTotal?: number;
    referents?: Set<AdherentDto>;
    nomSalle?: string;
}
export enum ActiviteDtoJourEnum {
    Monday = 'MONDAY',
    Tuesday = 'TUESDAY',
    Wednesday = 'WEDNESDAY',
    Thursday = 'THURSDAY',
    Friday = 'FRIDAY',
    Saturday = 'SATURDAY',
    Sunday = 'SUNDAY'
};



