/**
 * API Adhésion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActiviteNm1Dto { 
    id?: number;
    activiteId?: number;
    groupe?: string;
    groupeFiltre?: string;
    nom?: string;
    tarif?: number;
    horaire?: string;
    salle?: string;
}

