/**
 * API Adhésion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TribuDto } from './tribu';
import { AccordDto } from './accord';
import { NotificationDto } from './notification';
import { AdhesionDto } from './adhesion';
import { UserDto } from './user';
import { ActiviteNm1Dto } from './activite-nm1';


export interface AdherentDto { 
    id?: number;
    prenom?: string;
    nom?: string;
    genre?: string;
    telephone?: string;
    naissance?: string;
    lieuNaissance?: string;
    adresse?: string;
    codePostal?: string;
    ville?: string;
    adresseRepresentant?: boolean;
    telephoneRepresentant?: boolean;
    emailRepresentant?: boolean;
    mineur?: boolean;
    completAdhesion?: boolean;
    accords?: Array<AccordDto>;
    representant?: AdherentDto;
    derniereVisites?: Array<NotificationDto>;
    tribu?: TribuDto;
    adhesions?: Set<AdhesionDto>;
    activitesNm1?: Array<ActiviteNm1Dto>;
    user?: UserDto;
}

