/**
 * API Adhésion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccordDto } from './accord';
import { ActiviteDto } from './activite';
import { PresenceDto } from './presence';


export interface AdhesionDto { 
    id?: number;
    tarif?: number;
    position?: number;
    dejaLicencie?: boolean;
    validPaiementSecretariat?: boolean;
    validDocumentSecretariat?: boolean;
    statutActuel?: string;
    remarqueSecretariat?: string;
    inscrit?: boolean;
    flag?: boolean;
    majoration?: boolean;
    rappel?: boolean;
    dateAjoutPanier?: string;
    dateChangementStatut?: string;
    accords?: Array<AccordDto>;
    activite?: ActiviteDto;
    surClassement?: ActiviteDto;
    presences?: Array<PresenceDto>;
    valide?: boolean;
    enCours?: boolean;
    enAttente?: boolean;
}

