/**
 * API Adhésion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './user';


export interface NotificationDto { 
    id?: number;
    date?: string;
    user?: UserDto;
    raison?: string;
}

