/**
 * API Adhésion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalleDto } from './salle';
import { AdherentDto } from './adherent';


export interface PlanificationHebdomadaireDto { 
    id?: number;
    jour?: PlanificationHebdomadaireDtoJourEnum;
    horaireDebut?: string;
    duree?: number;
    descriptif?: string;
    salle?: SalleDto;
    profs?: Set<AdherentDto>;
    referents?: Set<AdherentDto>;
    nbSeancesTotal?: number;
    nbSeancesRealisees?: number;
}
export enum PlanificationHebdomadaireDtoJourEnum {
    Monday = 'MONDAY',
    Tuesday = 'TUESDAY',
    Wednesday = 'WEDNESDAY',
    Thursday = 'THURSDAY',
    Friday = 'FRIDAY',
    Saturday = 'SATURDAY',
    Sunday = 'SUNDAY'
};



