/**
 * API Adhésion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PresenceDto { 
    id?: number;
    presence?: boolean;
    presencePrevue?: boolean;
    dateModification?: string;
    seanceId?: number;
}

