/**
 * API Adhésion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleDto { 
    id?: number;
    name?: RoleDtoNameEnum;
}
export enum RoleDtoNameEnum {
    RoleUser = 'ROLE_USER',
    RoleSecretaire = 'ROLE_SECRETAIRE',
    RoleBureau = 'ROLE_BUREAU',
    RoleAdministrateur = 'ROLE_ADMINISTRATEUR',
    RoleAdmin = 'ROLE_ADMIN',
    RoleComptable = 'ROLE_COMPTABLE',
    RoleProf = 'ROLE_PROF',
    RoleReferent = 'ROLE_REFERENT'
};



