/**
 * API Adhésion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDto } from './role';
import { NotificationDto } from './notification';


export interface UserDto { 
    id?: number;
    username: string;
    roles?: Set<RoleDto>;
    emailValid?: boolean;
    sessionVersion?: number;
    notifs?: Set<NotificationDto>;
}

